export type Category = 'All' | 'Explainer Ads' | 'AI Ads' | 'Brand Films' | 'Social Media';

export interface PortfolioVideo {
  id: number;
  title: string;
  category: Category;
  thumbnail: string;
  duration: string;
  client: string;
  videoUrl?: string;
}

export const portfolioVideos: PortfolioVideo[] = [
  {
    id: 1,
    title: 'Product Launch Campaign',
    category: 'Explainer Ads',
    thumbnail: 'https://images.pexels.com/photos/3587620/pexels-photo-3587620.jpeg?auto=compress&cs=tinysrgb&w=800',
    duration: '0:45',
    client: 'TechCorp',
  },
  {
    id: 2,
    title: 'Brand Story Video',
    category: 'Brand Films',
    thumbnail: 'https://images.pexels.com/photos/3938022/pexels-photo-3938022.jpeg?auto=compress&cs=tinysrgb&w=800',
    duration: '1:20',
    client: 'StyleHouse',
  },
  {
    id: 3,
    title: 'AI-Powered Ad Spot',
    category: 'AI Ads',
    thumbnail: 'https://images.pexels.com/photos/3588365/pexels-photo-3588365.jpeg?auto=compress&cs=tinysrgb&w=800',
    duration: '0:30',
    client: 'NexaAI',
  },
  {
    id: 4,
    title: 'Social Reel Series',
    category: 'Social Media',
    thumbnail: 'https://images.pexels.com/photos/3714901/pexels-photo-3714901.jpeg?auto=compress&cs=tinysrgb&w=800',
    duration: '0:15',
    client: 'GlowBrand',
  },
  {
    id: 5,
    title: 'Service Explainer',
    category: 'Explainer Ads',
    thumbnail: 'https://images.pexels.com/photos/3747465/pexels-photo-3747465.jpeg?auto=compress&cs=tinysrgb&w=800',
    duration: '1:00',
    client: 'FinEdge',
  },
  {
    id: 6,
    title: 'Generative AI Commercial',
    category: 'AI Ads',
    thumbnail: 'https://images.pexels.com/photos/3938013/pexels-photo-3938013.jpeg?auto=compress&cs=tinysrgb&w=800',
    duration: '0:30',
    client: 'FutureStack',
  },
  {
    id: 7,
    title: 'Lifestyle Brand Film',
    category: 'Brand Films',
    thumbnail: 'https://images.pexels.com/photos/3975517/pexels-photo-3975517.jpeg?auto=compress&cs=tinysrgb&w=800',
    duration: '2:00',
    client: 'Lumière Co.',
  },
  {
    id: 8,
    title: 'Instagram Story Ads',
    category: 'Social Media',
    thumbnail: 'https://images.pexels.com/photos/3848382/pexels-photo-3848382.jpeg?auto=compress&cs=tinysrgb&w=800',
    duration: '0:15',
    client: 'UrbanWear',
  },
  {
    id: 9,
    title: 'App Promo Video',
    category: 'Explainer Ads',
    thumbnail: 'https://images.pexels.com/photos/3714896/pexels-photo-3714896.jpeg?auto=compress&cs=tinysrgb&w=800',
    duration: '0:45',
    client: 'AppForge',
  },
  {
    id: 10,
    title: 'Neural Ad Campaign',
    category: 'AI Ads',
    thumbnail: 'https://images.pexels.com/photos/3748221/pexels-photo-3748221.jpeg?auto=compress&cs=tinysrgb&w=800',
    duration: '0:30',
    client: 'Synapse Labs',
  },
  {
    id: 11,
    title: 'Corporate Brand Story',
    category: 'Brand Films',
    thumbnail: 'https://images.pexels.com/photos/3975518/pexels-photo-3975518.jpeg?auto=compress&cs=tinysrgb&w=800',
    duration: '3:00',
    client: 'VisionCorp',
  },
  {
    id: 12,
    title: 'TikTok Ad Pack',
    category: 'Social Media',
    thumbnail: 'https://images.pexels.com/photos/3848383/pexels-photo-3848383.jpeg?auto=compress&cs=tinysrgb&w=800',
    duration: '0:15',
    client: 'TrendWave',
  },
  {
    id: 13,
    title: 'Explainer Video 1',
    category: 'Explainer Ads',
    thumbnail: 'https://images.pexels.com/photos/3587620/pexels-photo-3587620.jpeg?auto=compress&cs=tinysrgb&w=800',
    duration: '0:45',
    client: 'Client 1',
    videoUrl: 'https://drive.google.com/file/d/1Ef2L6G-8WD2c9Yd3OmUWQ6u8UsIdSg0p/preview',
  },
  {
    id: 14,
    title: 'Explainer Video 2',
    category: 'Explainer Ads',
    thumbnail: 'https://images.pexels.com/photos/3938022/pexels-photo-3938022.jpeg?auto=compress&cs=tinysrgb&w=800',
    duration: '0:50',
    client: 'Client 2',
    videoUrl: 'https://drive.google.com/file/d/1AUjJeloJkeoNmLsSUF_U31XvqO886duh/preview',
  },
  {
    id: 15,
    title: 'Explainer Video 3',
    category: 'Explainer Ads',
    thumbnail: 'https://images.pexels.com/photos/3588365/pexels-photo-3588365.jpeg?auto=compress&cs=tinysrgb&w=800',
    duration: '0:55',
    client: 'Client 3',
    videoUrl: 'https://drive.google.com/file/d/1a3AOorp4UAHohlrXSPhJ6Q0NRNtBwcPt/preview',
  },
  {
    id: 16,
    title: 'Explainer Video 4',
    category: 'Explainer Ads',
    thumbnail: 'https://images.pexels.com/photos/3714901/pexels-photo-3714901.jpeg?auto=compress&cs=tinysrgb&w=800',
    duration: '0:45',
    client: 'Client 4',
    videoUrl: 'https://drive.google.com/file/d/1uWaj1ne93JxU2TsTuwpguH7t9GEqqapm/preview',
  },
  {
    id: 17,
    title: 'Explainer Video 5',
    category: 'Explainer Ads',
    thumbnail: 'https://images.pexels.com/photos/3747465/pexels-photo-3747465.jpeg?auto=compress&cs=tinysrgb&w=800',
    duration: '0:50',
    client: 'Client 5',
    videoUrl: 'https://drive.google.com/file/d/15T6LHJ8KT3jWCHYITY9K4o8GGzOKIUXZ/preview',
  },
  {
    id: 18,
    title: 'Explainer Video 6',
    category: 'Explainer Ads',
    thumbnail: 'https://images.pexels.com/photos/3938013/pexels-photo-3938013.jpeg?auto=compress&cs=tinysrgb&w=800',
    duration: '0:48',
    client: 'Client 6',
    videoUrl: 'https://drive.google.com/file/d/1dD29IMW10n3_rsmpORs841D96t5Bc6Ag/preview',
  },
  {
    id: 19,
    title: 'Explainer Video 7',
    category: 'Explainer Ads',
    thumbnail: 'https://images.pexels.com/photos/3975517/pexels-photo-3975517.jpeg?auto=compress&cs=tinysrgb&w=800',
    duration: '0:52',
    client: 'Client 7',
    videoUrl: 'https://drive.google.com/file/d/1_81mV4aVVssqaVB-8JuDNzcBH6AcKeyW/preview',
  },
  {
    id: 20,
    title: 'Explainer Video 8',
    category: 'Explainer Ads',
    thumbnail: 'https://images.pexels.com/photos/3848382/pexels-photo-3848382.jpeg?auto=compress&cs=tinysrgb&w=800',
    duration: '0:46',
    client: 'Client 8',
    videoUrl: 'https://drive.google.com/file/d/1szP2lDoJqvUv1z1WQ6Ua5YrVlnfnni03/preview',
  },
  {
    id: 21,
    title: 'Explainer Video 9',
    category: 'Explainer Ads',
    thumbnail: 'https://images.pexels.com/photos/3714896/pexels-photo-3714896.jpeg?auto=compress&cs=tinysrgb&w=800',
    duration: '0:49',
    client: 'Client 9',
    videoUrl: 'https://drive.google.com/file/d/1xG1U3oipmGgV1_kExhRjIFR9dcZjT_jf/preview',
  },
  {
    id: 22,
    title: 'Explainer Video 10',
    category: 'Explainer Ads',
    thumbnail: 'https://images.pexels.com/photos/3748221/pexels-photo-3748221.jpeg?auto=compress&cs=tinysrgb&w=800',
    duration: '0:51',
    client: 'Client 10',
    videoUrl: 'https://drive.google.com/file/d/149Q-da-7mYwkW5ahJUq7QUHBehzykLYa/preview',
  },
  {
    id: 23,
    title: 'Explainer Video 11',
    category: 'Explainer Ads',
    thumbnail: 'https://images.pexels.com/photos/3975518/pexels-photo-3975518.jpeg?auto=compress&cs=tinysrgb&w=800',
    duration: '0:47',
    client: 'Client 11',
    videoUrl: 'https://drive.google.com/file/d/1D7g8s0b2amFK8Rhep12YarIyg5BSZJTh/preview',
  },
  {
    id: 24,
    title: 'Explainer Video 12',
    category: 'Explainer Ads',
    thumbnail: 'https://images.pexels.com/photos/3587621/pexels-photo-3587621.jpeg?auto=compress&cs=tinysrgb&w=800',
    duration: '0:53',
    client: 'Client 12',
    videoUrl: 'https://drive.google.com/file/d/1pyjGf9lhvx2rr3bdUIKBr0zOhE4X6reZ/preview',
  },
  {
    id: 25,
    title: 'Explainer Video 13',
    category: 'Explainer Ads',
    thumbnail: 'https://images.pexels.com/photos/3938023/pexels-photo-3938023.jpeg?auto=compress&cs=tinysrgb&w=800',
    duration: '0:44',
    client: 'Client 13',
    videoUrl: 'https://drive.google.com/file/d/1SmL9bQ8f8vVoKvQMDvkbYjREwJCijiud/preview',
  },
  {
    id: 26,
    title: 'Explainer Video 14',
    category: 'Explainer Ads',
    thumbnail: 'https://images.pexels.com/photos/3588366/pexels-photo-3588366.jpeg?auto=compress&cs=tinysrgb&w=800',
    duration: '0:50',
    client: 'Client 14',
    videoUrl: 'https://drive.google.com/file/d/1dX2ewbCVGb94T6lXafCAKTqWBD602S6x/preview',
  },
  {
    id: 27,
    title: 'Explainer Video 15',
    category: 'Explainer Ads',
    thumbnail: 'https://images.pexels.com/photos/3714902/pexels-photo-3714902.jpeg?auto=compress&cs=tinysrgb&w=800',
    duration: '0:48',
    client: 'Client 15',
    videoUrl: 'https://drive.google.com/file/d/1Xwu0TzhtdIocip3PCFgLzAuCQCtBjyfv/preview',
  },
];

export const categories: Category[] = ['All', 'Explainer Ads', 'AI Ads', 'Brand Films', 'Social Media'];
